using Atlas.Common.GeneticData.PhenotypeInfo;
using Atlas.Common.Public.Models.GeneticData.PhenotypeInfo;

namespace Atlas.MatchingAlgorithm.Test.Validation.TestData.Models.Hla
{
    /// <summary>
    /// Test data is generated by taking a full set of TGS typed allele data (genotype), and artificially lowering the typing resolution
    /// </summary>
    public class Genotype
    {
        public PhenotypeInfo<TgsAllele> Hla;
    }
}