using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Atlas.Common.Public.Models.GeneticData;
using Atlas.Common.Public.Models.GeneticData.PhenotypeInfo;
using Atlas.MatchPrediction.Config;
using Atlas.MatchPrediction.ExternalInterface.Models.HaplotypeFrequencySet;
using Atlas.MatchPrediction.Models;
using Atlas.MatchPrediction.Services.HaplotypeFrequencies;

namespace Atlas.MatchPrediction.Services.GenotypeLikelihood;

public interface IDiplotypeLikelihoodCalculator
{
    /// <summary>
    /// Calculates the likelihood of a given diplotype based on the frequencies of its constituent haplotypes in the provided frequency set.
    /// </summary>
    /// <param name="diplotype">
    /// string HLA data must be at the same typing resolution as the frequency set provided, as no conversions will take place as part of this lookup.
    ///
    /// "Diplotype" here means that this should be used when the phase of the genotype is already known.
    /// (for example - if a collection of possible genotypes have been generated by combining haplotypes from the selected haplotype frequency set, rather
    /// than via independent expansion of input patient/donor hla - then the phase will be known)
    ///
    /// No further expansion will be performed to account for phase.
    /// </param>
    /// <param name="frequencySet"></param>
    /// <param name="allowedLoci"></param>
    /// <returns></returns>
    public Task<decimal> CalculateLikelihoodForDiplotype(
        PhenotypeInfo<string> diplotype,
        HaplotypeFrequencySet frequencySet,
        ISet<Locus> allowedLoci);
    
}

public class DiplotypeLikelihoodCalculator: IDiplotypeLikelihoodCalculator
{
    private readonly IHaplotypeFrequencyService haplotypeFrequencyService;
    public DiplotypeLikelihoodCalculator(
        IHaplotypeFrequencyService haplotypeFrequencyService
        )
    {
        
        this.haplotypeFrequencyService = haplotypeFrequencyService;
    }
    /// <inheritdoc />
    public async Task<decimal> CalculateLikelihoodForDiplotype(
        PhenotypeInfo<string> diplotype,
        HaplotypeFrequencySet frequencySet,
        ISet<Locus> allowedLoci)
    {
        var haplotypes = new Diplotype(diplotype);
        var excludedLoci = LocusSettings.MatchPredictionLoci.Except(allowedLoci).ToHashSet();

        var isEveryLocusHomozygous = GetHeterozygousLoci(diplotype, allowedLoci).Count == 0;
        var homozygosityCorrectionFactor = isEveryLocusHomozygous ? 1 : 2;
            
        haplotypes.Item1.Frequency = await haplotypeFrequencyService.GetFrequencyForHla(frequencySet.Id, haplotypes.Item1.Hla, excludedLoci);
        haplotypes.Item2.Frequency = await haplotypeFrequencyService.GetFrequencyForHla(frequencySet.Id, haplotypes.Item2.Hla, excludedLoci);

        return haplotypes.Item1.Frequency * haplotypes.Item2.Frequency * homozygosityCorrectionFactor;
    }
        
    private static List<Locus> GetHeterozygousLoci(PhenotypeInfo<string> genotype, ISet<Locus> allowedLoci)
    {
        var heterozygousLoci = new List<Locus>();

        genotype.EachLocus((locus, locusInfo) =>
        {
            if (locusInfo.Position1 != locusInfo.Position2 && allowedLoci.Contains(locus))
            {
                heterozygousLoci.Add(locus);
            }
        });

        return heterozygousLoci;
    }
}