// <auto-generated />
using Atlas.DonorImport.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Atlas.DonorImport.Data.Migrations
{
    [DbContext(typeof(DonorContext))]
    [Migration("20200512085524_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Atlas.DonorImport.Data.Models.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("A_1");

                    b.Property<string>("A_2");

                    b.Property<string>("B_1");

                    b.Property<string>("B_2");

                    b.Property<string>("C_1");

                    b.Property<string>("C_2");

                    b.Property<string>("DPB_1");

                    b.Property<string>("DPB_2");

                    b.Property<string>("DQB1_1");

                    b.Property<string>("DQB1_2");

                    b.Property<string>("DRB1_1");

                    b.Property<string>("DRB1_2");

                    b.Property<int>("DonorId");

                    b.Property<int>("DonorType");

                    b.Property<string>("Ethnicity");

                    b.Property<string>("Hash");

                    b.Property<int>("RegistryCode");

                    b.HasKey("Id");

                    b.ToTable("Donors");
                });
#pragma warning restore 612, 618
        }
    }
}
